import { FormEvent, useEffect, useMemo, useState } from "react";
import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowUpRight, Code2, Database, Layers3, Menu, Moon, MoveRight, Palette, Send, Sun, X, Zap } from "lucide-react";
import { toast } from "sonner";
import BunnySignature from "@/components/BunnySignature";
import { useTheme } from "@/contexts/ThemeContext";
import { trpc } from "@/lib/trpc";
import { supabase } from "@/lib/supabase";

const projects = [
  { title: "FoamX", type: "E-COMMERCE", tags: ["React", "Product", "Commerce"], tone: "orange", image: "/assets/northstar-commerce.jpg", description: "A premium automotive-care product site for clean, confident conversion.", live: "https://foamx.netlify.app" },
  { title: "Siyara Designer Studio", type: "RETAIL + MANUFACTURING", tags: ["Brand site", "Catalog", "Enquiry"], tone: "violet", image: "/assets/signal-operations.jpg", description: "A warm digital storefront and manufacturing presence for a Hyderabad fashion studio.", live: "https://siyara-designer-studio.netlify.app/" },
  { title: "Venky's", type: "FOOD + E-COMMERCE", tags: ["Storytelling", "Organic", "Store"], tone: "green", image: "/assets/morrow-studio.jpg", description: "An organic spice brand experience rooted in tradition and built for modern kitchens.", live: "https://venkeys-store.netlify.app/" },
  { title: "Dune Bar & Kitchen", type: "HOSPITALITY", tags: ["Restaurant", "Reservations", "Events"], tone: "sand", image: "/assets/northstar-commerce.jpg", description: "An immersive rooftop restaurant site with menu, events, gallery, and table reservations.", live: "https://dune-bar-restaurant.netlify.app" },
  { title: "More websites, more in progress", type: "MORE BUILDS", tags: ["Websites", "Digital products"], tone: "more", image: "/assets/signal-operations.jpg", description: "And more websites we created across product, retail, hospitality, and digital experiences.", live: "#contact" },
];
const filters = ["ALL", "E-COMMERCE", "RETAIL + MANUFACTURING", "FOOD + E-COMMERCE", "HOSPITALITY", "MORE BUILDS"];
const services = [
  { icon: <Code2 />, title: "FULL-STACK BUILDS", copy: "From first route to production-ready backend, I build the parts that make a product work." },
  { icon: <Palette />, title: "DIGITAL DIRECTION", copy: "A sharp visual system, clear interaction language, and a product people remember." },
  { icon: <Zap />, title: "AI-ASSISTED VELOCITY", copy: "AI accelerates exploration. Architecture, judgment, testing, and craft stay human-led." },
  { icon: <Layers3 />, title: "PRODUCT REFINEMENT", copy: "Debugging, performance, accessibility, and polish that turn a good idea into a dependable one." },
];
const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: .65, ease: [0.23, 1, 0.32, 1] as const } } };
const stagger = { hidden: {}, visible: { transition: { staggerChildren: .09 } } };

function SectionLabel({ number, children }: { number: string; children: string }) { return <div className="section-label"><span>{number}</span><span>{children}</span></div>; }
function ScrollSection({ id, children, className = "" }: { id: string; children: React.ReactNode; className?: string }) { return <section id={id} className={className}>{children}</section>; }
function ProjectPreview({ project }: { project: { title: string; live: string; image: string } }) { const [failed, setFailed] = useState(false); const [loading, setLoading] = useState(true); useEffect(() => { if (project.live === "#contact") return; const timeout = window.setTimeout(() => { setLoading(false); setFailed(true); }, 8000); return () => window.clearTimeout(timeout); }, [project.live]); if (project.live === "#contact") return <a className="preview-fallback" href={project.live}><img className="project-image" src={project.image} alt={`${project.title} project preview`} /><span>SEE MORE BUILDS <ArrowUpRight /></span></a>; return !failed ? <div className="project-live-frame"><iframe className="project-iframe" src={project.live} title={`${project.title} live preview`} loading="lazy" onLoad={() => setLoading(false)} onError={() => { setLoading(false); setFailed(true); }} />{loading && <div className="preview-loading" role="status">LOADING LIVE PREVIEW…</div>}<a className="live-preview-link" href={project.live} target="_blank" rel="noreferrer">OPEN LIVE PREVIEW <ArrowUpRight /></a></div> : <a className="preview-fallback" href={project.live} target="_blank" rel="noreferrer"><img className="project-image" src={project.image} alt={`${project.title} project preview`} /><span>OPEN LIVE PREVIEW <ArrowUpRight /></span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const { theme, toggleTheme } = useTheme();
  const [active, setActive] = useState("home");
  const [filter, setFilter] = useState("ALL");
  const [contentProjects, setContentProjects] = useState(projects);
  const [contentServices, setContentServices] = useState(services);
  const [contentSkills, setContentSkills] = useState({ FRONTEND: ["HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Next.js", "Responsive UI", "Motion"], BACKEND: ["Node.js", "Express", "REST APIs", "Auth", "Supabase", "PostgreSQL", "SQL", "Firebase"] });
  const [cmsError, setCmsError] = useState("");
  const [form, setForm] = useState({ name: "", email: "", message: "", kind: "contact" });
  const [siteContent, setSiteContent] = useState({ contact_email: "hello@bunny.build", about: "I'm Bunny, a full-stack web developer and freelancer focused on creating modern websites and digital experiences for businesses." });
  const { scrollYProgress } = useScroll();
  const progress = useSpring(scrollYProgress, { stiffness: 120, damping: 30 });
  const submit = trpc.contact.submit.useMutation({ onSuccess: () => { toast.success("Message received. I’ll be in touch soon."); setForm({ name: "", email: "", message: "", kind: "contact" }); }, onError: () => toast.error("Something went wrong. Please try again.") });
  const visibleProjects = useMemo(() => filter === "ALL" ? contentProjects : contentProjects.filter(p => p.type === filter), [filter, contentProjects]);

  useEffect(() => { if (!supabase) return; Promise.all([supabase.from("projects").select("title,type,description,live_url,image_url,tags,published,sort_order").eq("published", true).order("sort_order"), supabase.from("site_settings").select("key,value").in("key", ["contact_email", "about"]), supabase.from("services").select("title,description,published,sort_order").eq("published", true).order("sort_order"), supabase.from("skills").select("name,group_name,published,sort_order").eq("published", true).order("sort_order")]).then(([projectResult, settingsResult, serviceResult, skillResult]) => { if (projectResult.error || settingsResult.error || serviceResult.error || skillResult.error) setCmsError("Some live content could not be loaded. Showing the latest saved defaults."); if (projectResult.data?.length) setContentProjects(projectResult.data.map((p: any, i: number) => ({ title: p.title, type: p.type, description: p.description, live: p.live_url || "#contact", image: p.image_url || projects[i % projects.length].image, tags: p.tags || [], tone: i % 3 === 0 ? "orange" : i % 3 === 1 ? "violet" : "green" }))); if (settingsResult.data?.length) setSiteContent(v => ({ ...v, ...Object.fromEntries(settingsResult.data.map((row: any) => [row.key, row.value])) })); if (serviceResult.data?.length) setContentServices(serviceResult.data.map((s: any, i: number) => ({ ...services[i % services.length], title: s.title, copy: s.description }))); if (skillResult.data?.length) { const next = { FRONTEND: skillResult.data.filter((s: any) => s.group_name === "FRONTEND").map((s: any) => s.name), BACKEND: skillResult.data.filter((s: any) => s.group_name !== "FRONTEND").map((s: any) => s.name) }; setContentSkills(v => ({ FRONTEND: next.FRONTEND.length ? next.FRONTEND : v.FRONTEND, BACKEND: next.BACKEND.length ? next.BACKEND : v.BACKEND })); } }).catch(() => setCmsError("Some live content could not be loaded. Showing the latest saved defaults.")); }, []);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id); }), { rootMargin: "-30% 0px -55%" });
    ["home", "about", "process", "skills", "work", "services", "contact"].forEach(id => { const el = document.getElementById(id); if (el) observer.observe(el); });
    return () => observer.disconnect();
  }, []);
  const navTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };
  const onSubmit = async (e: FormEvent) => { e.preventDefault(); if (!form.name || !form.email || !form.message) { toast.error("Please complete all fields."); return; } if (supabase) { const { error } = await supabase.from("contact_messages").insert({ name: form.name, email: form.email, message: form.message, kind: form.kind }); if (error) { toast.error(error.message); return; } toast.success("Message received. I’ll be in touch soon."); setForm({ name: "", email: "", message: "", kind: "contact" }); return; } submit.mutate(form); };

  return <div className="site-shell">{cmsError && <div className="cms-notice" role="status">{cmsError}</div>}
    <motion.div className="scroll-progress" style={{ scaleX: progress }} />
    <header className="site-nav"><div className="nav-inner"><button className="brand-lockup" onClick={() => navTo("home")} aria-label="Go home"><span className="nav-signature"><BunnySignature /></span></button><nav className="desktop-links">{["about", "skills", "work", "services", "contact"].map((id, i) => <button className={active === id ? "active" : ""} key={id} onClick={() => navTo(id)}><span>0{i + 1}</span>{id.toUpperCase()}</button>)}</nav><div className="nav-actions"><button className="theme-toggle" onClick={() => toggleTheme?.()} aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} mode`} aria-pressed={theme === "light"}><span className="theme-toggle-track"><span className="theme-toggle-thumb">{theme === "dark" ? <Moon /> : <Sun />}</span></span><span className="theme-toggle-label">{theme === "dark" ? "DARK" : "LIGHT"}</span></button><button className="menu-toggle" onClick={() => setMenuOpen(v => !v)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></div></div>{menuOpen && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mobile-menu">{["home", "about", "skills", "work", "services", "contact"].map((id, i) => <button key={id} onClick={() => navTo(id)}><span>0{i + 1}</span>{id.toUpperCase()}<ArrowUpRight /></button>)}</motion.div>}</header>

    <ScrollSection id="home" className="hero"><div className="hero-grid" /><div className="hero-copy"><motion.div initial="hidden" animate="visible" variants={reveal} className="eyebrow"><span className="status-dot" /> AVAILABLE FOR SELECT PROJECTS <span className="eyebrow-line" /></motion.div><motion.h1 initial="hidden" animate="visible" transition={{ delay: .1 }} variants={reveal}>FULL-STACK<br /><em>DEVELOPER</em><br /><span>& DIGITAL BUILDER.</span></motion.h1><motion.p initial="hidden" animate="visible" transition={{ delay: .2 }} variants={reveal}>I build modern websites and digital experiences that help businesses look better, work smarter, and grow online.</motion.p><motion.div initial="hidden" animate="visible" transition={{ delay: .3 }} variants={reveal} className="hero-actions"><button className="button button-primary" onClick={() => navTo("work")}>VIEW MY WORK <ArrowUpRight /></button><button className="button button-ghost" onClick={() => navTo("contact")}>LET'S WORK TOGETHER <MoveRight /></button></motion.div><motion.div initial="hidden" animate="visible" transition={{ delay: .4 }} variants={reveal} className="hero-micro"><span>AI-ASSISTED DEVELOPMENT</span><span>FULL-STACK ENGINEERING</span><span>FREELANCE WEB DEVELOPMENT</span></motion.div></div><div className="hero-art"><div className="orb orb-one" /><div className="orb orb-two" /><div className="logo-halo"><img src="/assets/bunny-logo.png" alt="Bunny geometric rabbit logo" /></div><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="art-caption"><span>01 / 04</span><span>CRAFTED IN THE OPEN</span></div></div><div className="hero-bottom"><span>SCROLL TO EXPLORE</span><span className="scroll-line" /><span>© 2026</span></div></ScrollSection>

    <ScrollSection id="about" className="section about-section"><div className="container"><SectionLabel number="01" children="A LITTLE ABOUT ME" /><div className="about-layout"><motion.h2 initial="hidden" whileInView="visible" viewport={{ once: true, amount: .3 }} variants={reveal}>I DON'T JUST BUILD<br /><span>WEBSITES.</span><br />I BUILD DIGITAL<br /><span>EXPERIENCES.</span></motion.h2><motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={reveal} className="about-copy"><p className="lead">{siteContent.about}</p><p>I combine coding, design thinking, AI-assisted development, and modern web technologies to turn ideas into functional digital products. AI is the accelerator; the architecture, decisions, customization, testing, and final craft are mine.</p><div className="signature">BUNNY <span>— DIGITAL BUILDER</span></div></motion.div></div></div></ScrollSection>

    <ScrollSection id="process" className="section process-section"><div className="container"><SectionLabel number="02" children="FROM IDEA → LAUNCH" /><motion.div className="process-grid" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .2 }} variants={stagger}>{[["01", "DISCOVER", "Understand the business, audience, goals, and requirements."], ["02", "DESIGN", "Create the visual direction and user experience."], ["03", "BUILD", "Develop with modern technologies and AI-assisted workflows."], ["04", "REFINE", "Test, debug, optimize, and polish."], ["05", "DEPLOY", "Launch the final product with confidence."]].map(([n, t, c]) => <motion.div variants={reveal} className="process-card" key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p><MoveRight /></motion.div>)}</motion.div></div></ScrollSection>

    <ScrollSection id="skills" className="section skills-section"><div className="container"><SectionLabel number="03" children="THE TOOLKIT" /><div className="skills-head"><h2>BUILT FOR THE<br /><span>WHOLE PICTURE.</span></h2><p>The stack is a means to an end: focused, adaptable, and chosen around the product.</p></div><div className="skill-groups"><div className="skill-group"><Code2 /><h3>FRONTEND</h3><div>{contentSkills.FRONTEND.map(s => <span key={s}>{s}</span>)}</div></div><div className="skill-group"><Database /><h3>BACKEND + DATA</h3><div>{contentSkills.BACKEND.map(s => <span key={s}>{s}</span>)}</div></div></div></div></ScrollSection>

    <ScrollSection id="work" className="section work-section"><div className="container"><SectionLabel number="04" children="SELECTED WORK" /><div className="work-head"><h2>IDEAS, <span>BUILT.</span></h2><div className="filter-row">{filters.map(f => <button key={f} className={filter === f ? "selected" : ""} onClick={() => setFilter(f)}>{f}</button>)}</div></div><motion.div layout className="project-grid">{visibleProjects.map((p, i) => <motion.article layout initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .08 }} className={`project-card tone-${p.tone}`} key={p.title}><div className="project-visual"><ProjectPreview project={p} /><div className="visual-grid" /><div className="visual-label">PROJECT / 0{i + 1}</div><div className="visual-shape" /></div><div className="project-meta"><div><span>{p.type}</span><h3>{p.title}</h3></div><div className="project-links"><a href={p.live} target="_blank" rel="noreferrer" aria-label={`${p.title} live site`}><ArrowUpRight /></a>{p.live !== "#contact" ? <a href={p.live} target="_blank" rel="noreferrer" aria-label={`Open ${p.title} live preview`}><Code2 /></a> : <a href={p.live} aria-label="See more websites"><ArrowUpRight /></a>}</div></div><p>{p.description}</p><div className="tag-row">{p.tags.map(t => <span key={t}>{t}</span>)}</div></motion.article>)}</motion.div></div></ScrollSection>

    <ScrollSection id="services" className="section services-section"><div className="container"><SectionLabel number="05" children="WHAT I DO" /><div className="services-head"><h2>MAKE IT <span>MATTER.</span></h2><p>Strategy, design, engineering, and the small details in between.</p></div><motion.div className="services-grid" initial="hidden" whileInView="visible" viewport={{ once: true }} variants={stagger}>{contentServices.map((s, i) => <motion.div variants={reveal} className="service-card" key={s.title}><div className="service-top"><span>0{i + 1}</span>{s.icon}</div><h3>{s.title}</h3><p>{s.copy}</p><ArrowUpRight className="service-arrow" /></motion.div>)}</motion.div></div></ScrollSection>

    <ScrollSection id="contact" className="section contact-section"><div className="container"><SectionLabel number="06" children="START A CONVERSATION" /><div className="contact-layout"><div><h2>HAVE A GOOD<br /><span>IDEA?</span><br />LET'S TALK.</h2><p>Tell me what you’re building, where it’s stuck, or where you want it to go.</p><a href={`mailto:${siteContent.contact_email}`} className="contact-email">{siteContent.contact_email} <ArrowUpRight /></a></div><form onSubmit={onSubmit} className="contact-form"><label>YOUR NAME<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Jane Smith" /></label><label>EMAIL ADDRESS<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="jane@company.com" /></label><label>REQUEST TYPE<select value={form.kind} onChange={e => setForm({ ...form, kind: e.target.value })}><option value="contact">General enquiry</option><option value="booking">Booking request</option></select></label><label>HOW CAN I HELP?<textarea value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="A few words about your project..." rows={4} /></label><button className="button button-primary" disabled={submit.isPending}>{submit.isPending ? "SENDING..." : "SEND MESSAGE"} <Send /></button></form></div></div></ScrollSection>

    <footer className="site-footer"><div className="footer-brand"><BunnySignature /></div><div className="footer-bottom"><span>© 2026 BUNNY. ALL RIGHTS RESERVED.</span><span>BUILD • CREATE • INSPIRE</span><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>BACK TO TOP <ArrowUpRight /></button></div></footer>
  </div>;
}
